### PR TITLE
Optimize healthbar drawing

### PR DESCRIPTION
**Pull request by LordReMiX**
Health-bar drawing in "objGlobalControl" Draw event is rather... naive.
It limits boss-fights to 40..50 FPS maximum when everything is full.
The "TestHall" with 4 bosses, it's ~20 FPS before anyone jumps down a hole.
An average stage is limited to ~80 FPS.
Health-bars hidden, 120..150 FPS is the minimum for the 4 bosses.
Stages can go with more than 200 FPS.
(Measurements from my computer, which is ~10 years old, but works nicely.)

This patch is two new sprites and a modified Draw event to use them.
Some quick testing shows that it is visually the same as the original method.
The slowdown seems gone.

### CODE REVIEW

**Comment by MightyPrinny** [comment]
can you try to optimize it without locking the healthbar to a fixed size?

**Comment by LordReMiX** [comment]
As the original uses 28 in several places, and sprHealthbarBackground has a size to match that, I thought the size is fixed. Unlocking that seems like a separate feature request. A feature where I don't know what constraints this has to fit.

**Comment by ginger-mochi** [comment]
Hey, sorry that I'm a bit late to this discussion!

You're right that 28 is generally hardcoded in a lot of places, but the hope is to eventually remove that hardcoded limit. However, having 28 hard-rendered sprites is not going to be easily extended to the arbitrary limit when that happens. You can use 28 as a hardcoded number, but if you can do this in a way that doesn't require 28 individual sprite frames to accomplish, that would be greatly preferred. For example, you could just use 8 subimages and repeat those as needed.

Also, it's better to keep the number of sprites low if possible since that helps a lot with save times TPAGE compile times.

**Comment by LordReMiX** [comment]
Rewritten. Moved parts of it to separate functions. Bar size is a parameter, currently a constant 28 everywhere, someone will replace those with variables.

**Comment by ginger-mochi** [comment]
It still feels like overkill to use 28 distinct sprites for this, when maybe a smaller number like 8 or 14 would be more reasonable w.r.t. TPAGE. However, since it is coded to extend past 28 smoothly, it looks good to be merged.

**Pull request merged**
